#Основной файл, где прописана группа хостов и их файлы с задачами.
---
- name: Master
  hosts: localhost
  gather_facts: false
  vars:
    file: "odii.exe"
  tasks:
  - name: Download the archive from FTP to Master
    get_url:
      url: "{{ ftp_url_master }}{{ file }}"
      dest: "{{ dest_download }}{{ file }}"
#file - название файла, который мы забираем с FTP

- name: Connecting host files hospital and hospital_FTP
  hosts: hospital:hospital_FTP
  gather_facts: no
#  serial: 5
  strategy: free
  tasks:
   - include: '/root/ansible/download/Hosts_upd/{{inventory_hostname}}.yml'
     with_items:
      - {dest: '/cgi-bin/odii.exe', file: 'odii.exe'}
#dest - путь до файла (/js/... или /cgi-bin/...) + название файла
#file - название файла 

- name: Send message to Telegram
  hosts: localhost
  gather_facts: yes
  vars:
    file: "odii.exe"
  tasks:
    - name: Download HTML page
      uri:
        url: "{{ check_ver }}{{ file }}?GETVERSION"
        return_content: yes
      register: html_page

    - name: Extract version using direct pattern matching
      set_fact:
        current_version: "{{ html_page.content }}"
        
    - name: Prepare message
      set_fact:
        telegram_message: |
          Файл #{{ file }} обновлен ✅
          Версия: {{ current_version }}

    - name: Send message
      uri:
        url: "https://api.telegram.org/{{token_tg}}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ chat_id_tg }}"
          text: "{{ telegram_message }}"
          parse_mode: "HTML"
      run_once: true
      tags:
      - skip_message